import Head from 'next/head';
import React from 'react';
import Main from '../components/Main.jsx'
import Layout from '../components/Layout.jsx'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Tartendown Nurseries</title>
        <meta
          name='description'
          content='Generated by Christopher Mander Jeffrey Wentworth'
        />
      </Head>
    </div>
  );
}
